# Generated by Django 4.2.7 on 2024-02-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
